// Biblioteca de videos de técnica: el link de YouTube de cada ejercicio, elegido a mano por
// GIZE (en español, demostración directa). Solo se enlaza (se abre en YouTube): no se descarga
// ni se vuelve a subir nada. Si el coach pega su propio link en el ejercicio, manda el del coach.
// Cada lunes el workflow "Videos" revisa que sigan existiendo (scripts/verificar-videos.mjs).
//
// Clave: nombre del ejercicio como está en EX_DB (sin tildes ni mayúsculas, ver norm()).
// Valor: link del video.

const V = {
  "Press de banca plano (barra)": "https://www.youtube.com/shorts/HzkHpIIo4IA",
  "Press de banca inclinado (barra)": "https://www.youtube.com/shorts/g99l4KwY-vo",
  "Press de banca declinado": "https://www.youtube.com/shorts/HhkJLQiWpvg",
  "Press plano con mancuernas": "https://www.youtube.com/shorts/qW519gsE2M8",
  "Press inclinado con mancuernas": "https://www.youtube.com/shorts/tcw2c5dtqD4",
  "Press plano en Smith": "https://www.youtube.com/shorts/twxPcHp77RE",
  "Press inclinado en Smith": "https://www.youtube.com/shorts/XwjuCBcFXQQ",
  "Aperturas con mancuernas": "https://www.youtube.com/shorts/26TsSvfg28U",
  "Aperturas inclinadas": "https://www.youtube.com/shorts/CQx4FhzelMU",
  "Aperturas en máquina": "https://www.youtube.com/shorts/vz3hqBgk7mw",
  "Cruce de poleas": "https://www.youtube.com/shorts/Gm7lwbxi7kQ",
  "Vuelos en polea": "https://www.youtube.com/shorts/mAmmIi7JRWM",
  "Fondos en paralelas": "https://www.youtube.com/shorts/s5BLhbKWD3E",
  "Flexiones de brazos": "https://www.youtube.com/shorts/cWrJFIdTje0",
  "Press de pecho en máquina": "https://www.youtube.com/shorts/bdcKHTb-LGU",
  "Peck deck": "https://www.youtube.com/shorts/vz3hqBgk7mw",
  "Cruce de poleas descendente": "https://www.youtube.com/shorts/5k_BHoOsrKU",
  "Press declinado con mancuernas": "https://www.youtube.com/shorts/BG0Y3kX5v8Y",
  "Aperturas en polea baja": "https://www.youtube.com/shorts/oUEdlT7G0Uc",
  "Flexiones diamante": "https://www.youtube.com/shorts/NDqHE21IOgw",
  "Press de pecho en máquina inclinado": "https://www.youtube.com/shorts/XwjuCBcFXQQ",
  "Dominadas": "https://www.youtube.com/shorts/_9rGBwreteE",
  "Dominadas neutras": "https://www.youtube.com/shorts/0Io6FqUd1Sw",
  "Jalón al pecho": "https://www.youtube.com/shorts/sAYU5EvtXSo",
  "Jalón neutro": "https://www.youtube.com/shorts/ves4oPpWQAE",
  "Jalón en V": "https://www.youtube.com/shorts/Ks3yr_wl8WU",
  "Jalón en estocada": "https://www.youtube.com/shorts/fiYxH7lHBzI",
  "Remo con barra": "https://www.youtube.com/shorts/LeG-O6_EdQ8",
  "Remo Pendlay": "https://www.youtube.com/shorts/AD9MnA68oqw",
  "Remo unilateral con mancuerna": "https://www.youtube.com/shorts/msjE_AWixcM",
  "Remo en máquina": "https://www.youtube.com/shorts/gwKy4Ea2wog",
  "Remo en máquina unilateral": "https://www.youtube.com/shorts/Ol37ocDBdAU",
  "Remo en polea baja": "https://www.youtube.com/shorts/soxtqUNRt6E",
  "Hiperextensiones lumbares": "https://www.youtube.com/shorts/5zYz96GMfAg",
  "Remo neutro abierto en polea baja": "https://www.youtube.com/shorts/B4pkCS3jZuk",
  "Jalón prono": "https://www.youtube.com/shorts/sAYU5EvtXSo",
  "Remo T": "https://www.youtube.com/shorts/uLr8HcW_7ig",
  "Remo en polea baja unilateral": "https://www.youtube.com/shorts/Ol37ocDBdAU",
  "Remo alto en polea": "https://www.youtube.com/shorts/Ho0OJOTWp1g",
  "Pullover en polea": "https://www.youtube.com/shorts/5cqIDziQ5Ko",
  "Pullover con mancuerna": "https://www.youtube.com/shorts/V7Slg0kPPLU",
  "Remo con mancuerna en banco inclinado": "https://www.youtube.com/shorts/9u5yLR9zmAs",
  "Remo invertido": "https://www.youtube.com/watch?v=intBkUz1hgM",
  "Dominadas asistidas": "https://www.youtube.com/shorts/BOBowsKJvh4",
  "Dominadas asistidas en máquina": "https://www.youtube.com/shorts/BOBowsKJvh4",
  "Jalón supino": "https://www.youtube.com/shorts/VnLY_duYJKI",
  "Remo Meadows": "https://www.youtube.com/watch?v=yTqX3JHtwUY",
  "Rack pull": "https://www.youtube.com/shorts/ydUEFSCsChY",
  "Press militar con barra": "https://www.youtube.com/shorts/lAuH141eYE0",
  "Press Arnold": "https://www.youtube.com/shorts/GS8miQOMl2U",
  "Press de hombros con mancuernas": "https://www.youtube.com/shorts/R0f2Of6Sl2A",
  "Press de hombros en Smith": "https://www.youtube.com/shorts/wocA-bgEAZw",
  "Vuelos laterales con mancuernas": "https://www.youtube.com/shorts/wPkosHeBUGc",
  "Vuelos laterales en polea": "https://www.youtube.com/shorts/mAmmIi7JRWM",
  "Vuelos laterales en máquina": "https://www.youtube.com/shorts/WmdhjLZzEjM",
  "Vuelos posteriores": "https://www.youtube.com/shorts/4oiNyEogO4Q",
  "Posterior en máquina": "https://www.youtube.com/shorts/S5FCRI-lXAk",
  "Posterior en polea": "https://www.youtube.com/shorts/kNIZWlX-hTo",
  "Elevaciones frontales": "https://www.youtube.com/shorts/1RTg5Nb9atc",
  "Jalón a la cara": "https://www.youtube.com/shorts/Lz9rWJfGaQA",
  "Encogimientos de hombros": "https://www.youtube.com/shorts/0-KrI1Hqpk4",
  "Vuelos laterales sentado": "https://www.youtube.com/shorts/j2tjiP-YoDU",
  "Elevaciones laterales": "https://www.youtube.com/shorts/wPkosHeBUGc",
  "Vuelo lateral en polea (énfasis estiramiento)": "https://www.youtube.com/shorts/5N8CJU5UsYo",
  "Remo al mentón": "https://www.youtube.com/shorts/VOAwxHxdLg0",
  "Press landmine": "https://www.youtube.com/shorts/Ih7ioseCaSA",
  "Elevación Y en banco inclinado": "https://www.youtube.com/shorts/itvKYjCRZK0",
  "Press militar sentado": "https://www.youtube.com/shorts/MZPz2Vn51ig",
  "Rotación externa en polea": "https://www.youtube.com/shorts/BTb5gnkYk8g",
  "Curl con barra": "https://www.youtube.com/shorts/OrX-n9r-WKM",
  "Curl con barra Z": "https://www.youtube.com/shorts/pT-wvBPSMZU",
  "Curl con mancuernas": "https://www.youtube.com/shorts/WrpQYs_n_Pw",
  "Curl alternado": "https://www.youtube.com/shorts/ygb5M3lc-dc",
  "Curl martillo": "https://www.youtube.com/shorts/qScJnRNO6wk",
  "Curl predicador": "https://www.youtube.com/shorts/uO5OUPTT5fE",
  "Curl en banco inclinado": "https://www.youtube.com/shorts/koLVyY5pej0",
  "Curl en polea": "https://www.youtube.com/shorts/oJGSW0z5Hew",
  "Curl en polea detrás del cuerpo": "https://www.youtube.com/shorts/7kLT9OxHyw0",
  "Curl concentrado": "https://www.youtube.com/shorts/JM6T3kun48k",
  "Curl araña": "https://www.youtube.com/shorts/B3LBfyiJx1k",
  "Curl bíceps en polea baja frontal": "https://www.youtube.com/shorts/ORLIBnqcIII",
  "Curl Bayesian": "https://www.youtube.com/shorts/lU-_i3ccQp0",
  "Curl predicador en polea": "https://www.youtube.com/shorts/NfPUoyn-20w",
  "Curl martillo en polea": "https://www.youtube.com/shorts/VnyPUkrxBR0",
  "Curl en máquina": "https://www.youtube.com/shorts/K3VputefVE8",
  "Curl 21": "https://www.youtube.com/shorts/RadovrRJ7xc",
  "Curl con barra supino en polea": "https://www.youtube.com/shorts/_EIu8OySoao",
  "Press francés con barra": "https://www.youtube.com/shorts/CAUWI4sNPKk",
  "Press francés con mancuernas": "https://www.youtube.com/shorts/FgN0vyx8jNE",
  "Extensión en polea": "https://www.youtube.com/shorts/X7pe4Laknis",
  "Extensión con soga": "https://www.youtube.com/shorts/JVc1KAB_HLY",
  "Patada de tríceps": "https://www.youtube.com/shorts/QNW_TACPzPg",
  "Press cerrado": "https://www.youtube.com/shorts/qaul6unMSW8",
  "Fondos entre bancos": "https://www.youtube.com/shorts/wN_9d37DO4M",
  "Extensión sobre la cabeza": "https://www.youtube.com/shorts/9Ark9S11uXw",
  "Katana en polea": "https://www.youtube.com/shorts/4fROz8wpZe0",
  "Extensión de tríceps unilateral en polea": "https://www.youtube.com/shorts/me9suJxPrRY",
  "Fondos en máquina": "https://www.youtube.com/shorts/6DvQdto5NKk",
  "Extensión de tríceps en máquina": "https://www.youtube.com/shorts/n6r2TNcAb7g",
  "Press JM": "https://www.youtube.com/shorts/1v_WtGNauOQ",
  "Sentadilla libre": "https://www.youtube.com/shorts/NHD0vH7XXgw",
  "Sentadilla frontal": "https://www.youtube.com/shorts/YKKpfeP5ScM",
  "Sentadilla en Smith": "https://www.youtube.com/shorts/7cxG2c2j6es",
  "Sentadilla hack": "https://www.youtube.com/shorts/_K5qW_sENbg",
  "Prensa 45": "https://www.youtube.com/shorts/0-t5LejEP1c",
  "Prensa horizontal": "https://www.youtube.com/shorts/PBnh2I0nxmc",
  "Extensión de cuádriceps": "https://www.youtube.com/shorts/iNvPzf15KKA",
  "Extensión de cuádriceps a una pierna": "https://www.youtube.com/shorts/kG83qbQ5l4I",
  "Zancadas": "https://www.youtube.com/shorts/mlEfhtj-4_8",
  "Sentadilla búlgara": "https://www.youtube.com/shorts/OPtXZbqgYUc",
  "Sentadilla con mancuerna al pecho": "https://www.youtube.com/shorts/2KbVt1Gl0VM",
  "Subida al cajón": "https://www.youtube.com/shorts/EJixTTFnNSs",
  "Sentadilla sissy": "https://www.youtube.com/shorts/J78f55CdoKk",
  "Cuadricera": "https://www.youtube.com/shorts/iNvPzf15KKA",
  "Sentadilla goblet": "https://www.youtube.com/shorts/2KbVt1Gl0VM",
  "Sentadilla pendular": "https://www.youtube.com/shorts/RsSGq7aN_ww",
  "Sentadilla con cinturón": "https://www.youtube.com/shorts/v2uoheVQRi8",
  "Zancadas caminando": "https://www.youtube.com/shorts/tsyHY_g6LpI",
  "Zancada inversa": "https://www.youtube.com/shorts/uCyxYGkvKO4",
  "Sentadilla sumo": "https://www.youtube.com/shorts/EAc5IyMjmh8",
  "Curl femoral acostado": "https://www.youtube.com/shorts/B6t8MvbTtew",
  "Curl femoral sentado": "https://www.youtube.com/shorts/6IvQvWZmEsw",
  "Curl femoral de pie": "https://www.youtube.com/shorts/eSBHWdckw1c",
  "Peso muerto rumano": "https://www.youtube.com/shorts/li2Eecx-LCQ",
  "Peso muerto rumano con mancuernas": "https://www.youtube.com/shorts/3u9M3nh0C0g",
  "Peso muerto piernas rígidas": "https://www.youtube.com/shorts/EDaWUZnFKz8",
  "Peso muerto convencional": "https://www.youtube.com/shorts/A-R_fuvVgGM",
  "Buenos días": "https://www.youtube.com/shorts/7cpldMZjLOs",
  "Curl nórdico": "https://www.youtube.com/shorts/GzxNzNRy9T0",
  "Camilla de isquios": "https://www.youtube.com/shorts/B6t8MvbTtew",
  "Peso muerto rumano a una pierna": "https://www.youtube.com/shorts/7ulHtv30lxM",
  "Curl femoral con fitball": "https://www.youtube.com/shorts/sVP8-1Ikvko",
  "Empuje de cadera": "https://www.youtube.com/shorts/zaSzxo6xleY",
  "Empuje de cadera en máquina": "https://www.youtube.com/shorts/vvWdxTKTy2M",
  "Puente de glúteo": "https://www.youtube.com/shorts/FfXq0AUz_Xw",
  "Patada de glúteo en polea": "https://www.youtube.com/shorts/GvgL2NbOaKE",
  "Patada de glúteo en máquina": "https://www.youtube.com/shorts/HlrLyKsrV78",
  "Abductores": "https://www.youtube.com/shorts/xlp6FYwBFLU",
  "Abducción en polea": "https://www.youtube.com/shorts/KDF6U5GwA98",
  "Aductores": "https://www.youtube.com/shorts/BWS8lMtXU7I",
  "Peso muerto sumo": "https://www.youtube.com/shorts/EFfmRof0RZw",
  "Empuje de cadera a una pierna": "https://www.youtube.com/shorts/9BKxP6WfajY",
  "Patada de glúteo en cuadrupedia": "https://www.youtube.com/shorts/LCAYqAdZROA",
  "Caminata lateral con banda": "https://www.youtube.com/shorts/DhSbbJVQPGk",
  "Hiperextensión para glúteo": "https://www.youtube.com/shorts/rnMcVZPhUDM",
  "Step-up para glúteo": "https://www.youtube.com/shorts/Ey2H3-zmzSk",
  "Gemelos de pie": "https://www.youtube.com/shorts/goHLe1fninw",
  "Gemelos sentado": "https://www.youtube.com/shorts/amK4IUv7BsQ",
  "Gemelos en prensa": "https://www.youtube.com/shorts/_EkH6H7GNyY",
  "Gemelos en Smith": "https://www.youtube.com/shorts/Nqg_ECwg-bU",
  "Gemelos burro": "https://www.youtube.com/shorts/8VgdGrEu4Gk",
  "Gemelos a una pierna": "https://www.youtube.com/shorts/OCpCLsrYfUU",
  "Gemelos en máquina": "https://www.youtube.com/shorts/goHLe1fninw",
  "Elevación de tibial": "https://www.youtube.com/shorts/-pGwwrUWL4w",
  "Encogimiento abdominal": "https://www.youtube.com/shorts/YCsecXIjUoI",
  "Encogimiento declinado": "https://www.youtube.com/shorts/WNe8AHY3Hic",
  "Elevación de piernas": "https://www.youtube.com/shorts/TdaqT8KQihA",
  "Elevación de piernas colgado": "https://www.youtube.com/shorts/vsG3ufxXtUo",
  "Plancha": "https://www.youtube.com/shorts/KC-DK0qydqw",
  "Rueda abdominal": "https://www.youtube.com/shorts/knjliGWvGa4",
  "Encogimiento en polea": "https://www.youtube.com/shorts/1DpnrOWv1A4",
  "Giro ruso": "https://www.youtube.com/shorts/Xvm7zSiFyak",
  "Escaladores": "https://www.youtube.com/shorts/Fb79R7IUwYE",
  "Oblicuos": "https://www.youtube.com/shorts/_cdt_-Bhi48",
  "Plancha lateral": "https://www.youtube.com/shorts/fzLeV8X0Gb8",
  "Encogimiento invertido": "https://www.youtube.com/watch?v=Q6Xg48GUGfY",
  "Bicicleta abdominal": "https://www.youtube.com/shorts/cScwegLnI7Q",
  "Puntas a la barra": "https://www.youtube.com/shorts/qw_OrWlCq0s",
  "Plancha invertida": "https://www.youtube.com/shorts/Vfui9B2ekWM",
  "Bicho muerto": "https://www.youtube.com/shorts/fr0kWY9Z-j4",
  "Leñador en polea": "https://www.youtube.com/shorts/DBFGGIFG2o0",
  "Encogimiento en máquina": "https://www.youtube.com/shorts/VY3tyM1auOU",
  "Bandera": "https://www.youtube.com/watch?v=Q6Xg48GUGfY",
  "Abdominales en V": "https://www.youtube.com/shorts/7h4wBdOgAp0",
  "Crunch en banco": "https://www.youtube.com/shorts/WNe8AHY3Hic",
  "Pallof press": "https://www.youtube.com/shorts/iMrUsNVOyEs",
  "Elevación de rodillas en paralelas": "https://www.youtube.com/shorts/vehZfhyHjDI",
  "Plancha con toque de hombros": "https://www.youtube.com/shorts/auypDs3TVeM",
  "Curl de muñeca": "https://www.youtube.com/shorts/JrCRzibnz4Y",
  "Curl de muñeca invertido": "https://www.youtube.com/shorts/cRLJ86m00cU",
  "Curl invertido con barra": "https://www.youtube.com/shorts/HKawMPHNKmE",
  "Caminata del granjero": "https://www.youtube.com/shorts/iJ8pj3eef34",
  "Curl de antebrazo en polea": "https://www.youtube.com/shorts/u6ELoOSCZmg",
  "Curl de muñeca con mancuerna": "https://www.youtube.com/shorts/JrCRzibnz4Y",
  "Curl Zottman": "https://www.youtube.com/shorts/4atCzx_QIHY",
  "Enrollador de muñeca": "https://www.youtube.com/shorts/w0EhavNDR70",
  "Colgarse de la barra": "https://www.youtube.com/shorts/KMb6Szr6oLQ",
  "Pinza con disco": "https://www.youtube.com/shorts/SM_1mmEqPzY",
  "Extensión de muñeca con kettlebell": "https://www.youtube.com/watch?v=tdFTpTbk0Ag",
  "Curl de muñeca con barra": "https://www.youtube.com/watch?v=s5lhlt5FeP4",
  "Desviación cubital con mancuerna": "https://www.youtube.com/watch?v=3_ufQRMqBuU",
  "Pronación de antebrazo con mancuerna": "https://www.youtube.com/watch?v=k-TU6s_3_O0",
  "Flexión de cuello con disco": "https://www.youtube.com/shorts/nbIiMGnHdT4",
  "Extensión de cuello con disco": "https://www.youtube.com/shorts/vZf3-6iPBWU",
  "Flexión lateral de cuello": "https://www.youtube.com/shorts/PhoizxB7fFQ",
  "Flexión de cuello con arnés": "https://www.youtube.com/shorts/oVa0xrBPCog",
  "Puente de cuello": "https://www.youtube.com/shorts/4un4GRqJQQk",
  "Rotaciones de cuello": "https://www.youtube.com/shorts/wACiDNPO2aA",
};

// Otros nombres con los que aparece el mismo ejercicio (incluye los que se sacaron de la base,
// para que las rutinas que ya los tienen sigan mostrando video).
const ALIAS = {
  "Remo en barra T": "Remo T",
  "Prensa 45°": "Prensa 45",
  "Aductores en máquina": "Aductores",
  "Jalón unilateral en estocada": "Jalón en estocada",
  "Jalón con brazos rectos en polea": "Pullover en polea",
  "Jalón con brazos rectos y mancuerna": "Pullover con mancuerna",
  "Extensión de tríceps parado en polea": "Extensión en polea",
  "Sentadilla": "Sentadilla libre",
  "Press de banca": "Press de banca plano (barra)",
  "Hip thrust": "Empuje de cadera",
  "Hip thrust en máquina": "Empuje de cadera en máquina",
  "Face pull": "Jalón a la cara",
  "Dead bug": "Bicho muerto",
  "Paseo del granjero": "Caminata del granjero",
  "Plancha abdominal": "Plancha",
  "Plancha frontal": "Plancha",
  "Curl alternado con mancuernas": "Curl alternado",
  "Pullover": "Pullover en polea",
  "Remo gironda": "Remo en polea baja",
  "Polea al pecho": "Jalón al pecho",
  "Estocadas": "Zancadas",
  "Sillón de cuádriceps": "Extensión de cuádriceps",
  "Crunch abdominal": "Encogimiento abdominal",
  "Crunch en polea": "Encogimiento en polea",
  "Crunch invertido": "Encogimiento invertido",
  "Toes to bar": "Puntas a la barra",
  "Press francés": "Press francés con barra",
  "Fondos": "Fondos en paralelas",
  "Monster walk": "Caminata lateral con banda",
};

const norm = s => String(s || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[°º]/g, "").replace(/\s+/g, " ").trim();

const IDX = {};
Object.keys(V).forEach(k => { IDX[norm(k)] = V[k]; });
Object.keys(ALIAS).forEach(k => { const v = V[ALIAS[k]]; if(v && !IDX[norm(k)]) IDX[norm(k)] = v; });

// Video de la biblioteca para un nombre de ejercicio: { url, channel } o null.
export function libVideo(name){
  const v = IDX[norm(name)];
  return v && /^https:\/\//i.test(v) ? { url: v, channel: "" } : null;
}

// Id del video de YouTube (para comparar links escritos distinto: shorts, watch, youtu.be).
const ytId = u => { const m = /(?:shorts\/|v=|youtu\.be\/|embed\/)([\w-]{11})/.exec(String(u || "")); return m ? m[1] : String(u || ""); };
const LIB_IDS = new Set(Object.values(V).map(ytId));

// El video que ve el cliente: el link del coach si hay; si no, el de la biblioteca.
// Antes, al cambiar un ejercicio por otro, quedaba el link del anterior (vuelos en polea con
// el video de vuelos sentado). Ahora el link se borra al cambiarlo, y para las rutinas que ya
// quedaron así: no se usa un link que era de otro ejercicio (videoFor) ni un video de la
// biblioteca que no es el de este ejercicio.
export function exVideo(ex){
  const lib = libVideo(ex && ex.name);
  if(ex && ex.video && /^https:\/\//i.test(ex.video)){
    // Si el coach lo pegó para este ejercicio (videoFor), va el suyo aunque sea uno de la biblioteca.
    if(ex.videoFor) return norm(ex.videoFor) === norm(ex.name) ? { url: ex.video, channel: "" } : lib;
    const id = ytId(ex.video);
    if(LIB_IDS.has(id) && !(lib && ytId(lib.url) === id)) return lib;
    return { url: ex.video, channel: "" };
  }
  return lib;
}

// Al cambiar un ejercicio por otro: el video y el audio que eran del anterior no van.
export function dropExMedia(ex){ if(ex){ delete ex.video; delete ex.videoFor; delete ex.audio; delete ex.audioSecs; } }
